// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW11OUj0XJt1FmlHsLgOhxNe-NPUnD6QQ',
    appId: '1:68778743183:web:3ed4eb47e7622013b8a7fa',
    messagingSenderId: '68778743183',
    projectId: 'celebray-fa7ae',
    authDomain: 'celebray-fa7ae.firebaseapp.com',
    storageBucket: 'celebray-fa7ae.firebasestorage.app',
    measurementId: 'G-M9S7KNV3C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPRgizyZrQFgT2e0zUOHR-4JL-_mQxbQI',
    appId: '1:68778743183:android:03963effdbb08719b8a7fa',
    messagingSenderId: '68778743183',
    projectId: 'celebray-fa7ae',
    storageBucket: 'celebray-fa7ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzBd7lqXuBOW_oeIAbshwjpDHYm3eNhFM',
    appId: '1:68778743183:ios:c29c531de218cadab8a7fa',
    messagingSenderId: '68778743183',
    projectId: 'celebray-fa7ae',
    storageBucket: 'celebray-fa7ae.firebasestorage.app',
    iosBundleId: 'com.example.celebray',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzBd7lqXuBOW_oeIAbshwjpDHYm3eNhFM',
    appId: '1:68778743183:ios:c29c531de218cadab8a7fa',
    messagingSenderId: '68778743183',
    projectId: 'celebray-fa7ae',
    storageBucket: 'celebray-fa7ae.firebasestorage.app',
    iosBundleId: 'com.example.celebray',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW11OUj0XJt1FmlHsLgOhxNe-NPUnD6QQ',
    appId: '1:68778743183:web:2035ac1a22a31d2bb8a7fa',
    messagingSenderId: '68778743183',
    projectId: 'celebray-fa7ae',
    authDomain: 'celebray-fa7ae.firebaseapp.com',
    storageBucket: 'celebray-fa7ae.firebasestorage.app',
    measurementId: 'G-23Y4WT5BM7',
  );
}
